##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-settings-daemon
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - gettext
    - g++
    - git
    - gobject-introspection
    - ctk-doc-tools
    - iso-codes
    - libcanberra-ctk3-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libfontconfig1-dev
    - libglib2.0-dev
    - libctk-3-dev
    - libnotify-dev
    - libnss3-dev
    - libpolkit-agent-1-dev
    - libpolkit-gobject-1-dev
    - libpulse-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxext-dev
    - libxi-dev
    - libxklavier-dev
    - libxrandr-dev
    - libxt-dev
    - libxml2-utils
    - libtool
    - make
    - policykit-1
    - x11proto-kb-dev

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master
  - ./install-from-git https://github.com/cafe-desktop/cafe-desktop master
  - ./install-from-git https://github.com/cafe-desktop/libcafekbd master
  - ./install-from-git https://github.com/cafe-desktop/libcafemixer master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--prefix=/usr --enable-pulse --enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/cafe-applets/raw/master/cpufreq/pixmaps/cpufreq-100.png; fi
