##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # cafe B-D: libkanberra-ctk3-dev libctk-3-dev libcafe-desktop-dev libcafekbd-dev libcafemixer-dev cafe-common
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - gettext
    - g++
    - git
    - gobject-introspection
    - gtk-doc-tools
    - iso-codes
    - libdbus-glib-1-dev
    - libdconf-dev
    - libfontconfig1-dev
    - libglib2.0-dev
    - libnotify-dev
    - libnss3-dev
    - libpolkit-agent-1-dev
    - libpolkit-gobject-1-dev
    - libpulse-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxext-dev
    - libxi-dev
    - libxklavier-dev
    - libxrandr-dev
    - libxt-dev
    - libxml2-utils
    - libtool
    - make
    - wget
    - x11proto-kb-dev

    #packages required for libkanberra
    - gnome-pkg-tools
    - libltdl-dev
    - libasound2-dev
    - libvorbis-dev
    - libtdb-dev
    - libgstreamer1.0-dev

before_scripts:
  - ./html-cppcheck
  - ./debrepo-install 'libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0'
  - ./install-from-git https://github.com/cafe-desktop/libkanberra master
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master
  - ./install-from-git https://github.com/cafe-desktop/cafe-desktop master
  - ./install-from-git https://github.com/cafe-desktop/libcafekbd master
  - ./install-from-git https://github.com/cafe-desktop/libcafemixer master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-pulse --enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/cafe-applets/raw/master/cpufreq/pixmaps/cpufreq-100.png; fi
