.\" CAFE manpages
.\" csd_datetime-mechanism -man
.\"
.TH csd_datetime-mechanism 1 "Oct 2014" "" "CAFE-SETTINGS-DAEMON"
.SH NAME
csd_datetime-mechanism \- set system time via D-Bus
.SH SYNOPSIS
csd_datetime-mechanism
.SH DESCRIPTION
The \fIcsd_datetime-mechanism\fR is used for setting the system time via D-Bus.
.
\fIcsd_datetime-mechanism\fR is a D-Bus wrapper that gets executed via D-Bus with root privileges.
The execution of \fIcsd_datetime-mechanism\fR gets triggered via the CAFE clock applet.
.SH AUTHOR
This manual page has been written by Vangelis Mouhtsis <vangelis@gnugr.org> and Mike Gabriel <mike.gabriel@das-netzwerkteam.de>.
It has been originally written for the Debian project (but may be used by others).
